language: node_js

install:  
  - npm ci 

cache:
  npm: true 

jobs:
  include:
    - stage: test
      script: 
        - commitlint-travis
    - stage: pr
      script:
        - npx danger ci 
    - stage: deploy      
      script: 
        - npx semantic-release

stages:
  - name: test
    if: type IN (push, pull_request) AND tag IS blank
  - name: deploy
    if: type IN (push) AND branch = master